'use strict';
// [PL_MCP_P1] Bundles the in-app MCP server (mcp/server/src/index.js) into one script,
// war/scripts/mcp-server.js (git-ignored), which circuitjs.html loads in the page context and
// the Maven resource copy puts into target/site. Run with `npm run build:mcp`; scripts/dev_n_build.js
// runs it before every GWT build and devmode.
//
// Target: the embedded Node 18.0.0 / Chromium 101 of NW.js 0.64.1. Node built-ins stay
// `require(...)` calls (the NW page context provides `require`); the bundle must not contain
// `require("crypto")` — the release runtime's Node has no OpenSSL (PL_MCP Phase 0).

const path = require('path');
const fs = require('fs');

const ROOT = path.resolve(__dirname, '..', '..');
const ENTRY = path.join(__dirname, 'src', 'index.js');
const OUTFILE = path.join(ROOT, 'war', 'scripts', 'mcp-server.js');

function buildMcpServer() {
  const esbuild = require('esbuild');
  const t0 = Date.now();
  esbuild.buildSync({
    entryPoints: [ENTRY],
    outfile: OUTFILE,
    bundle: true,
    platform: 'node',
    format: 'iife',
    target: ['node18.0', 'chrome101'],
    legalComments: 'none',
    logLevel: 'warning',
    banner: { js: '/* CircuitJS1 in-app MCP server — generated by mcp/server/build.js; do not edit. */' },
  });
  const text = fs.readFileSync(OUTFILE, 'utf8');
  if (/require\(\s*["'](node:)?crypto["']\s*\)/.test(text)) {
    throw new Error('mcp-server.js requires Node crypto, which the release runtime lacks');
  }
  const kb = Math.round(fs.statSync(OUTFILE).size / 1024);
  console.log(`MCP server bundle: ${path.relative(ROOT, OUTFILE)} (${kb} KB, ${Date.now() - t0} ms)`);
  return OUTFILE;
}

module.exports = { buildMcpServer, OUTFILE };

if (require.main === module) {
  try {
    buildMcpServer();
  } catch (e) {
    console.error('MCP server bundle failed:', e.message);
    process.exit(1);
  }
}
